### ISSUE TITLE
This project feel to be AWESOME!!! But..

### ISSUE THREAD

**Issue by RealAquilus** [PanosK92/Directus3D#1] opened 2016-09-11 20:57 UTC
I found this only today and i fell that is AWESOME, really man you are a god! A new engine with the best license ever existed (MIT) and with the Unity UI!!!!
But... I have windows 7 i can't start this, sadly.....
Can you do a port to windows 7 too? Please man really i want to use this awesome engine!!
PS. a .txt with a building tutorial should be helpful for programmer that want to understand how an engine is made like me.
Thanks anyway for this fantastic project!!!!

Sorry for my english i'm studying for improve it.

**Comment by PanosK92** [comment] 2016-09-12 01:32
Thanks for your kind words! 
The reason you can't run it is probably Qt (editor dependency), It should be as easy as adding/replacing an extra Qt DLL or two but I haven't done any serious testing on Windows 7. With enough determination you can get it running on your own, but I will take care of the issue the moment I get some free time. Do you get any messages when the engine fails to start? 

I would like to add any used third party libraries inside this repository, this will make it as is as downloading and building (more or less). When I do this I will write the building tutorial you mentioned.

**Comment by RealAquilus** [comment] 2016-09-12 08:37
Can not find the entry point CreateFile2 the procedure in the dynamic link library KERNEL32.dll.

Really thanks! I will wait for the Win7 port and the tutorial :D

**Comment by PanosK92** [comment] 2016-09-12 16:22
I found the cause of the error, I fixed it, recompiled the engine and re-uploaded the binaries. I would appreciate if you could test it and let me know if it runs as I don't have a Windows 7 machine around.

**Comment by PanosK92** [comment] 2016-09-29 16:50
Thanks for helping me solve this, since we confirmed you got it working, I am closing this issue.

**Closed by PanosK92** 2016-09-29 16:50 UTC
